### ISSUE TITLE
Allow 2 digit HUC TVP search for USGS Plugin

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#16]
USGS allows searching for data points by 2 digit HUC codes.  Let's enable 2 digit huc code searches.  This will require the plugin for TVP search to handle two different Daily Values queries to NWIS. One that searches `sites` and the other `huc`

**Comment by dschristianson** [comment]
The plan is to change the USGS plugin to get data with both 2-digit huc codes as well as the >8 digit station codes. We will use the same infrastructure for both cases. 

Impacts: Elevation data for the monitoring feature will be lost.

Additional changes to dealing with the return:
- the statistic (mean, min, max) will be interpreted from the return
- the data quality might need to be reworked -- we filter the data if the checked flag per variable is not returned
