### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by dschristianson** [BASIN-3D/basin3d#183]
Documentation updates:

- [x] Add USGS Plugin documentation on the plugins page
- [x] Clean up outdated documentation in the USGS plugin
- [x] Add documentation on the data models: monitoring feature, measurement TVP time series observation
- [x] Review in code documentation and clean up if needed, especially wrt the API

**Comment by vchendrix** [comment]
Closed in 99ab51cd117b203c3c9a8bf8f4b6f79be88e0713
