### ISSUE TITLE
GitHub Action Error - Artifact Upload Conflict

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#199]
The GitHub Action `actions/upload-artifact@v4` encountered an error during the artifact upload process. The error indicates that an artifact with the specified name already exists in the current workflow run, causing a conflict.

**Error Message:**
```
Run actions/upload-artifact@v4

With the provided path, there will be 30 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

**Steps to Reproduce:**
1. Trigger the GitHub Action workflow that includes the `actions/upload-artifact@v4` step.
2. Ensure that the artifact name specified in the upload step is the same as an existing artifact in the current workflow run.

**Expected Behavior:**
The artifact should be uploaded successfully without any conflicts.

**Actual Behavior:**
The upload process fails with a `409 Conflict` error because an artifact with the same name already exists.

**Possible Solutions:**
1. **Rename the Artifact:** Modify the artifact name to ensure it is unique for each workflow run.
2. **Conditional Upload:** Implement a check to see if an artifact with the same name already exists before attempting to upload.
3. **Cleanup Previous Artifacts:** Ensure that previous artifacts are cleaned up or overwritten if they are no longer needed.

**Comment by dschristianson** [comment]
This error is happening again. PR #206

**Comment by dschristianson** [comment]
I was able to get by this error by running each version individually. This makes me think maybe there is a collision happening, e.g., 2 versions (say 3.9 and 3.10) are trying to write artifacts at the same time??

**Comment by vchendrix** [comment]
> I was able to get by this error by running each version individually. This makes me think maybe there is a collision happening, e.g., 2 versions (say 3.9 and 3.10) are trying to write artifacts at the same time??

Interesting, I thought I fixed that with `overwrite: true`

**Comment by vchendrix** [comment]
> > > I was able to get by this error by running each version individually. This makes me think maybe there is a collision happening, e.g., 2 versions (say 3.9 and 3.10) are trying to write artifacts at the same time??
> > 
> > 
> > Interesting, I thought I fixed that with `overwrite: true`
> 
> I wonder if we can change these to run serially.

Here is the documentation for the gh action https://github.com/actions/upload-artifact

**Comment by vchendrix** [comment]
@dschristianson this might be a solution https://github.com/actions/upload-artifact/issues/480#issuecomment-1937762859
