### ISSUE TITLE
Synthesized timeseries data into pandas df returned with NaN values, from Examples

### ISSUE THREAD

**Issue by heycatwonton** [BASIN-3D/basin3d#34]
**Describe the bug**
After synthesizing timeseries data into pandas df, my returned df gave me the data column values as NaN (not a number) as opposed to a numeric values like in the Examples in Sphinx documentation. My Timestamp column also has a time format (hh:mm:ss ?) and it does not in Examples.

**To Reproduce**
1. Go to https://github.com/iNAIADS/basin3d/blob/master/README.md
2. Scroll down to 'Documentation'
3. Follow steps to generate and open documentation, then open Examples in the documentation
4. Follow steps in 'Get Timeseries Data' 
5. See error after entering the command `usgs_df`

**Expected behavior**
Expected to see values in the data frame and expected output to look like the one in Examples. 

**Screenshots**

**Get Timeseries Data in Examples in Generated Sphinx Documentation**

![error screenshot 1](https://cdn1.bbcode0.com/uploads/2021/1/20/07f2cd0de6c34b591ef876dacde3a90e-full.png)

**Output with dataframe showing NaN values after synthesizing timeseries data**

![error screenshot 2](https://cdn1.bbcode0.com/uploads/2021/1/20/5d2fb7f1f35c76d1de2761d69979950e-full.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Python 3.8
 - Version 3

**Comment by vchendrix** [comment]
Addressed in f0a68fa1c2aadc624d5d341e11599698b5ecaae6
