### ISSUE TITLE
Documentation: Intro

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#37]
Add text for intro section discussin BASIN-3D is and why to use it.  Consider renaming this section to "Why use BASIN-3D" or something similar.

Ideas:

- What does it enable?
- Leverage Science Gateways Posters, paper
- Who should use it?
       - Scientist
       - Web services and developer: point to django repo

**Comment by heycatwonton** [comment]
closing issue manually because Github did not close it automatically
