### ISSUE TITLE
Documentation: BASIN-3D Concepts

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#38]
Write documentation that explains the key concepts in BASIN-3D that a beginning user would need to understand.  This could be things such as "What is a Monitoring Feature?" and explaning the plugin concept.

**Comment by dschristianson** [comment]
Draft documentation: https://docs.google.com/document/d/1yqqvEMq2XZ2s3-UDybNomcbX1Rgh59wUHWll92wYKVo/
