### ISSUE TITLE
Documentation: User facing API

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#39]
Replace the "Models" section in the documentation with documentation on the user facing API.

**Comment by dschristianson** [comment]
Draft documentation: https://docs.google.com/document/d/16FGCfweiAmW3lcDI1nw52dG2hY9EnCkvt2fQzFGMAcQ/

**Comment by heycatwonton** [comment]
Proofread and rework front page

**Comment by heycatwonton** [comment]
closing issue manually because Github did not close it automatically
