### ISSUE TITLE
Documentation: Fix autogenerated documentation

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#41]
Move all auto generated documentation to "Library Reference" Section and make sure it generated properly.

**Comment by heycatwonton** [comment]
- ~install graphviz~ DONE
- ~add graphviz to requirements.txt in /docs~ DONE
- investigate `Unknown directive type "automodule"` in: models.rst, api.rst
- investigate `Unknown directive type "toctree"` in: index.rst
- investigate `Undefined substitution referenced: "release"` in: index.rst
- investigate `WARNING: html_static_path entry '_static' does not exist` when making doc
