### ISSUE TITLE
Documentation: Contact Us section

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#42]
Add content to the Contact Us section.  This still needs to be determined.  

Ideas:  

- emails to contact
- pointer to logging issue in github
- link to contributing?
- are their other ways in Github to communicate with users?

**Comment by heycatwonton** [comment]
[](https://docs.google.com/document/d/1H44Qr2ggD02IDc3de7Nf2i3MNspEDHKYoGumUPlv_Q8/edit)

**Comment by heycatwonton** [comment]
[](https://docs.google.com/document/d/1H44Qr2ggD02IDc3de7Nf2i3MNspEDHKYoGumUPlv_Q8/edit)

**Comment by heycatwonton** [comment]
1. we'll use github discussions as form of contact
2. Refactor README and set up contributing.md first, then point it here in Contact Us

**Comment by heycatwonton** [comment]
closing issue manually because Github did not close it automatically
