### ISSUE TITLE
Enable CI for multiple python version - Refactor tests to separate out integration and unit tests

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#46]
Currently, the tests run agains the USGS. This is problematic as we want to scale up to run concurrent tests for multiple python version (3.7, 3.8, 3.9).  If we run these concurrently, we run the risk of failure due to what seems to be throttling by the data source.  We need to refactor the tests to separate out integration test from unit tests.  The unit tests should retain the 90% test coverage value.

**Comment by dschristianson** [comment]
Related to #10 which suggests considering changing doc tests dependent on USGS
