### ISSUE TITLE
Map Salinity in the USGS plugin

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#88]
**Is your feature request related to a problem? Please describe.**
Salinity (SAL) is defined in the [basin3d hydrology variables](https://github.com/BASIN-3D/basin3d/blob/main/basin3d/data/basin3d_variables_hydrology.csv#L149). However, it is not mapped in the USGS plugin. (See [mapping_usgs.csv](https://github.com/BASIN-3D/basin3d/blob/main/basin3d/plugins/mapping_usgs.csv))

**Describe the solution you'd like**
Figure out which salinity parameter code to map from USGS. See parameter code query [here](https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes?pm_group=Physical&pm_search=salinity&casrn_search=&radio_pm_search=srsname_search&srsname_search=Salinity&format=html_table&show=parameter_group_nm&show=parameter_nm&show=casrn&show=srsname&show=parameter_units)

**Comment by charuleka** [comment]
Use SC for specific conductance not salinity

**Comment by vchendrix** [comment]
Closing based on the previous comment. SAL mapping is not needed

> Use SC for specific conductance not salinity
